state            = ANIMAL_STATE.IDLE;
dir              = choose(DIR.LEFT, DIR.RIGHT, DIR.UP, DIR.DOWN);
frame_anim       = 0;
anim_frames      = 4;
move_speed       = 0.6;
hp               = 1;
max_hp           = 1;
chase_speed_mult = 1.5;
chase_timer      = 0;
chase_timer_max  = 600;
attack_damage    = 1;
attack_cooldown  = 0;
attack_cooldown_max = 30;
attack_range     = 32;
hurt_flash_timer = 0;
is_dying         = 0;
death_anim_frames = 48;
idle_timer       = irandom_range(60, 240);
wander_steps     = 0;
max_wander_steps = irandom_range(30, 120);
product_drops    = [];
image_speed      = 0;

snd_hurt   = undefined;
snd_death  = undefined;
snd_attack = undefined;
snd_move   = undefined;
snd_idle   = undefined;
snd_timer  = 0;
if (variable_instance_exists(self, "enemy_key") && is_string(enemy_key) && enemy_key != "") {
    var _snd = global.enemy_data[$ enemy_key];
    if (_snd != undefined) {
        if (variable_struct_exists(_snd, "snd_hurt"))   snd_hurt   = _snd.snd_hurt;
        if (variable_struct_exists(_snd, "snd_death"))  snd_death  = _snd.snd_death;
        if (variable_struct_exists(_snd, "snd_attack")) snd_attack = _snd.snd_attack;
        if (variable_struct_exists(_snd, "snd_move"))   snd_move   = _snd.snd_move;
        if (variable_struct_exists(_snd, "snd_idle"))   snd_idle   = _snd.snd_idle;
    }
}
